### ISSUE TITLE
Get Canvas' font size

### ISSUE THREAD

**Issue by porres** [porres/completion-plugin#19]
no need to use our own font size...

We can just get the actual canvas' font size 

for investigating, here's dialog_font.tcl

        if {[winfo exists ${mytoplevel}.text]} {
            set font [lindex [${mytoplevel}.text.internal cget -font] 0]
            if { ${font} eq {} } {
                set font $::font_family
            }
            ${mytoplevel}.text.internal configure -font [list $font $myfontsize]
        }

**Comment by porres** [comment]
> for investigating, here's dialog_font.tcl

This sets font for Pd's window, we needed the canvas size!

It seems we can't get the canvas' font size from the tcl/tk side... so I don't know what to do...

I'm gonna ping @umlaeute and @sebshader for help/guidance

**Comment by porres** [comment]
I know this is easy and trivial to get on the C side, just ask for "glist_getfont()"

but how to do this on the tcl/tk plugin?

I do have an external in ELSE called [fontsize] that gives me the canvas' font size. 

I see "patcherize" comes with compiled objects, is it for a similar reason? Could offer 'fontsize' compiled along with the completion plugin and communicate with it? This question is aimed at @umlaeute

**Comment by umlaeute** [comment]
> but don;t get pdwindow's size and the actual patch size

i cannot parse this sentence.

> I see "patcherize" comes with compiled objects, is it for a similar reason?

what similar reasons? patcherize does heavy work on the Pd-core side. the GUI plugin is just a minimal shim to add the menu entry and to auto-load the patcherize external.

**Comment by porres** [comment]
@umlaeute,  there's a setting for the font size in the completion-plugin, but it could just use the canvas' fontsize - with "glist_getfont()".

This information doesn't seem to be retrievable on the tcl/tk side of Pd, I wonder if I have to do something like patcherize and offer an external just to get the font size...

**Comment by umlaeute** [comment]
there currently is no way to directly query the font-size or a patch on the GUI side. (just check out the code for the font-dialog (or even simpler: the messages that go between Pd-core and Pd-GUI).

do you *really* need to know the font-size? or is it just eye-candy?
because an architecture-independent external is significantly *better* than a compiled external.

**Comment by porres** [comment]
I think I need it. Otherwise the settings need to be manually changed whenever you change font size or work on vc a patch of different font size...

**Comment by umlaeute** [comment]
but what for? so that things align nicely? is this something "nice-to-have" or something without which the completion-plugin will not work?

**Comment by porres** [comment]
The plug-in offers this font size In-N-Out's settings , but is kinda meaningless to me as you can't know what will work. It's like if pd had a font size settings for objects that needed to be changed to match patch font size. 

This is surely nice to have and we use font size for added gui boxes and iemguis... 

Right now it's just bad design and user experience

**Comment by umlaeute** [comment]
> Right now it's just bad design and user experience

what? having the drop-down displayed at a font-size of 12 when the patch uses a font-size of 14?

in any case, what I find it much worse UX, that there are weird suggestions like `plugin::rescan` and `plugin::debug` which i have never heard about. (obviously they are no autocompletion suggestions at all, but instead allow me to access some settings of the completion-plugin; but they look *identical* to ordinary suggestions even though they are not). and that right between `/~` and `<` there are some numbers (they obviously got there because of string sorting; but they look strangely out of place).

for the first issue you might just want to add a menu-entry rather than have it in the suggestions.

(this is with `0.48.0`, as `0.49.0` is broken for me (see #22).

**Comment by porres** [comment]
I agree and had already removed rescan/debug

**Comment by porres** [comment]
sorry, I was on the phone...

> what? having the drop-down displayed at a font-size of 12 when the patch uses a font-size of 14?

yup, and not only this, but specially having to adapt and set it accordingly to something that is set somewhere else that you shouldn't have to set, just grab the information from the canvas... 

but I see it isn't easily available from the tcl/tk side, unless we include changes to the core.

**Comment by porres** [comment]
>  right between /~ and < there are some numbers (they obviously got there because of string sorting; but they look strangely out of place).

sorry, i did not understand what you meant by this

**Comment by umlaeute** [comment]
>but I see it isn't easily available from the tcl/tk side, unless we include changes to the core.
>

Just to make sure: I think it if course desirable that the completion plugin users the same don't suppose as the surrounding patch.

However, as you discovered, there is currently no way to get this font-size without writing an external.

And I think the drawbacks of introducing a arch-dependent binary to get this functionality *heavily* outweighs the nicety of having automatic font sizes

**Comment by sebshader** [comment]
I wonder if one could use some kind of search to get the font metrics of some existing text in a canvas..
course, it wouldn't work w/ canvasses without any text yet..

**Comment by umlaeute** [comment]
there already is a `text` object: the one you want to autocomplete (it's empty, but it is there)

**Comment by porres** [comment]
> the drawbacks of introducing a arch-dependent binary to get this functionality heavily outweighs the nicety of having automatic font sizes

I see, well, I wonder then how crazy would it be to change the Pd core a bit so this easily obtainable...  

> I wonder if one could use some kind of search to get the font metrics of some existing text in a canvas...

or this or some other magic.

**Comment by umlaeute** [comment]
> > right between /~ and < there are some numbers (they obviously got there because of string sorting; but they look strangely out of place).
> 
> sorry, i did not understand what you meant by this

![complete-numbers](https://user-images.githubusercontent.com/214034/226143208-48974075-cbf5-494d-8610-ba63da033951.png)

but i now see that this came from `custom_completions/custom_completions.txt` https://github.com/porres/completion-plugin/blob/f4d58722238a95d32108b48f8c61ffff2e13f788/custom_completions/custom_completions.txt#L27-L33 and has been removed from the 0.49 release (which i wasn't able to test, due to #22; as of 0.49.1 thus problem has been solved)

**Comment by umlaeute** [comment]
> > I wonder if one could use some kind of search to get the font metrics of some existing text in a canvas...
> 
> or this or some other magic.


that looks actually pretty trivial to me.
you already get the current text with https://github.com/porres/completion-plugin/blob/38fe89fc33242c6de604fac58497793640aeecc6/completion-plugin.tcl#L722

you can also get the *exact* font specification with a very similar command:


```tcl
set font [$::current_canvas itemcget $::current_tag -font]
```

then you don't need to hard-code "Menlo" or "12" or discard the "bold" face

**Comment by porres** [comment]
thanks, works like a charm :) 

![Screen Shot 2023-03-18 at 19 56 53](https://user-images.githubusercontent.com/5360142/226144552-234ba48b-8751-4104-a690-47742a919120.png)

**Comment by umlaeute** [comment]
you're welcome.

however , https://github.com/porres/completion-plugin/commit/5f21936813d388a28a4d2aed93314063dc7daa0c ignores any `-font-face` and `-font-weight` options.
why?

**Comment by porres** [comment]
well, it's not like the plugin did allow us to set font face and weight before :)  but I get it, we can retrieve them as well and use it --> https://github.com/porres/completion-plugin/issues/26

**Comment by umlaeute** [comment]
> well, it's not like the plugin did allow us to set font face and weight before 

i didn't say it was a regression.

but i said:
> then you don't need to hard-code "Menlo" or "12" or discard the "bold" face

 :-)

**Comment by porres** [comment]
question, when someone changes pd's font to something funny or whatever, do all menus follow suit? Should I query which font is Pd running on to adopt into the 'completion' settings entry?

**Comment by sebshader** [comment]
No I don't think so. TCL/tk generally leaves that stuff too the window manager I believe

**Comment by sebshader** [comment]
Imo it would be cool if this were an option - the user either chooses a font size or you can 'use patch font'

**Comment by umlaeute** [comment]
> question, when someone changes pd's font to something funny or whatever, do all menus follow suit?

No they don't.
Instead, they are governed by font setting of the Pd-console.


> Should I query which font is Pd running on to adopt into the 'completion' settings entry?

Maybe, but...


*this* issue was about getting the font-size of the current canvas, in order for the completion pulldown to adjust to it.
Now the only reason I can see why you want this is, because you want the pulldown to appear consistent with the other objects in the patch, rather than with the menu or the Pd-console.

In this vein I suggested, that you should not only ensure that the font *size* matches the current canvas, but also the other font properties, like weight and face.

If you want to match the general menus instead, you should use the font specs of the menus (as found eg in the Pd-console text field. there's probably a variable for that, but I'm currently afk)

I don't think you should *ever* hardcode a specific font (or worse: two) if you want to have a consistent appearance with Pd.

**Comment by umlaeute** [comment]
> Imo it would be cool if this were an option - the user either chooses a font size or you can 'use patch font'

Out of interest: what would be the use case? (We could of course add options for the font colour and the spacing and the number of colons and what not, but is this a service to the user?)

**Comment by porres** [comment]
i wouldn't be a Pd guy if I wasn't fond of the KISS principle (Keep it Simple, Stupid)

**Comment by sebshader** [comment]
Well I agree w/ KISS design in the core but idk about plugins..
Perhaps in this case it would be best to put the 'get font properties' in a separate function that a user could easily overwrite in a personal *-plugin.tcl file. That way the plugin is simple but easily modifiable

**Comment by porres** [comment]
> Perhaps in this case it would be best to put the 'get font properties' in a separate proc that a user could easily overwrite in a personal *-plugin.tcl file.

send me a PR

as for the properties, they're almost completely vanished, now that I see that a shortcut for adding the library prefix is already implemented (did I proposed the that years ago? what a coincidence), we're left with the hotkey only... which could be hardcoded and documented...
