### ISSUE TITLE
fails to load if docsdir has not been loaded

### ISSUE THREAD

**Issue by umlaeute** [porres/completion-plugin#22]
i personally do not like the "docsdir" (global Pd document directory), so I disable it when it ever pops up (and i usually start Pd from the cmdline, which will omit loading the plugin).

Now, in these circumstances, the completion-plugin fails to load:

```
Loading plugin: .../completion-plugin/completion-plugin.tcl
[completion-plugin] version 0.49.0
-----------
UNHANDLED ERROR: can't read "::pd_docsdir::docspath": no such variable
    while executing
"set pathlist $::pd_docsdir::docspath/externals"
    (procedure "::completion::add_user_externals" line 17)
    invoked from within
"::completion::add_user_externals"
    (procedure "::completion::scan_all_completions" line 28)
    invoked from within
"::completion::scan_all_completions"
    (procedure "::completion::init" line 18)
    invoked from within
"::completion::init"
    ("uplevel" body line 1569)
    invoked from within
"uplevel #0 $tclcode"
FAILED TO LOAD .../completion-plugin/completion-plugin.tcl
-----------
```

i think the completion-plugin should not rely on docsdir being present.

**Comment by umlaeute** [comment]
well, and if it does rely on docsdir, then it should refuse to load with a proper error message, rather than a backtrace.

**Comment by porres** [comment]
where do your externals live then? I guess in such case we can try to look inside every folder in search paths

**Comment by porres** [comment]
I cannot reproduce this error, even if I disable documents directory

![Screen Shot 2023-03-18 at 01 09 51](https://user-images.githubusercontent.com/5360142/226084127-e3a1a4ef-a8c5-4a39-9832-a0c5706efbb1.png)

**Comment by umlaeute** [comment]
Then it's probably that you have to start Pd via the core (eg from the cmdline, launching the `.../bin/pd` binary directly. (I'm currently afk so i cannot test this)

**Comment by umlaeute** [comment]
> where do your externals live then?

I think a specific answer is not going to help.
However, they live in one of `$::sys_searchpath` and `$::sys_staticpath`.

(Many of them are actually installed system wide by my package manager)

> I guess in such case we can try to look inside every folder in search paths

Why only in /this/ case? Why do you dislike the standard search paths so much to actively remove support for them? (this is not a question whether these search paths are easily accessible on the system: If they are populated, then the user obviously found ways to populate them so why are they not allowed to use the completion plugin; if they are *not* populated then there's no content to ignore anyhow)

And yes, it is easy to use both the docsdir *and* paths in `$::sys_searchpath` resp `$::sys_staticpath`.
So please do not try to detect which of two exclusive modes should be used.

**Comment by porres** [comment]
> Many of them are actually installed system wide

what is to install them "system wide"?

**Comment by porres** [comment]
> Why do you dislike the standard search paths so much to actively remove support for them?

Ok, many questions, many issues, many implementation details. Let's go... 

One thing is that the way the plugin worked (or 'not quite worked') and what I understood about the system made me think it was unnecessary. So I was just trying to fix it and make it simpler and more efficient.

I didn't realize one would not use the suggested docs for externals and I do believe that with all changes and discussions we had that this was the new and good practice. Specially, it was considered that 'extra' was not a good place to mess with. I know forks like ceammc use it, and Pd-extended used it, by extension Purr Data uses it, not sure what plugdata uses, but these aren't tcl/tk and this is for Vanilla :) Now, the old way this plugin was behaving, it included Vanilla objects from 'extra' but was also searching for them and getting duplicates. It felt like a simple/wise decision to disable this.

The plugin had this 'folder depth' parameter that we'd use to tell it how deep inside folders we should look for more folders, but the way it was working here is that it would look for the 'pd/documents/externals' folder, then inside all folders that lived there, but since some of them were also added to the search path it would try and look deep inside them as well.

In short, for many years Pd just creates this folder and all externals are automatically thrown there by deken, so it felt like wise to follow this standard.

The mechanism for searching binaries was not only broken in the latest versions but it also didn't deal with so called 'monolihic' libraries. Changing for finding help files instead improved the system a lot. It isn't perfect, but the old way as even less perfect and it seems there is not a "perfect" way unless we design some system for libraries to tell Pd Vanilla what are their objects and work on all abandoned and existing libraries to do this... (this would also be nice for object menus).

It seems it's not trivial to get all of the externals because they can come in all sorts of ways, there's no real standard and eventually we're gonna miss special cases. Similarly, I now see it can also be tricky to get all libraries and design an intelligent system to grab them in all sorts of ways that people are allowed to do, be it for good reasons or not.

I still think that looking for the externals documents folder and then all of its containing folders is the way most people are using and are advised to manage externals for quite a few years now. It seems like a good default setting. It also seems like a good way to 'educate' people who aren't doing this for any special good reason (like a well knowledged power user could be doing), meaning that they wouldn't 'lose' any functionality or give up on anything by adopting the new suggested standard. 

Now, as for power users, we could a fallback to "other ways", but now I'm also thinking we could have a more sophisticated "advanced settings" to attend these special cases. And anyway, in order to better understand this situation in order to think about it, I was really curious about how your sophisticated setup is done, what are its use case and all. This is why I was asking.

Anyway, this would be in line to how the 'deken' plugin and Pd works these days. It suggests creating this folder and all externals are just downloaded there... this plugin could just follow suit... but I know 'deken' and Pd has 'advanced settings' for other cases so this one could also have them (and they'd be stored and saved for updates, so one would just do it once ideally). Perhaps it could query deken's settings as well... 

let us think and let me understand your setup please.

**Comment by porres** [comment]
I'm closing this issue as I think I have fixed this and created a fallback mechanism that will not only prevent the plugin from loading but will also perform a "deep scanning". Please test 0.49.1 to see if it is working, it should behave as 0.48.0 and also include its old issues by gathering duplicated objects.

we can keep, of course, discussing for a more sophisticated mechanism and advanced options.

**Comment by umlaeute** [comment]
> what is to install them "system wide"?

`apt-get install pd-cyclone` will install cyclone in a place where *all* users of the system can use it.
this might be not your workflow, but it is a bog-standard workflow on Linux distributions (here: Debian and derivatives).

> I didn't realize one would not use the suggested docs for externals and I do believe that with all changes and discussions we had that this was the new and good practice. Specially, it was considered that 'extra' was not a good place to mess with. 

no not really. the problem with `extra` is that macOS people have a hard time finding it (similar to `~/Library/Pd`).
as mentioned above, there are ways to install into `extra` without *messing* with it.


 > In short, for many years Pd just creates this folder and all externals are automatically thrown there by deken,

no they are not. `deken` installs to wherever you tell it to install to.
it will use docsdir as the default if it is available (but only if it is available). it will suggest and use all the other searchpaths as found in `$::sys_searchpath` resp `$::sys_staticpath` just as well.

> Now, as for power users, we could a fallback to "other ways", 

i think that `apt-get install pd-cyclone` has been established for about 20 years and is not "only for power users" - this is *the* standard way of installing externals on Debian (and derivatives, like Ubuntu).

> Anyway, this would be in line to how the 'deken' plugin and Pd works these days.

Pd doesn't work like this these days. Pd(-core) has a number of built-in search paths and the default docsdir is decidedly *not* among them.
Pd-GUI otoh does suggest the docsdir and adds it as an explicit search-path to Pd-core (if the user agrees with it).

---
but anyhow, i think this is mainly besides the point.

afaict there are two "issues" here:
- a deep scan for objects
- a search in all search-paths

my concern is with the second.
the problem you tried to solve when removing support for the second, appears to be performance issues with the 1st.
i'm not entirely sure what you mean with "deep scan" (and i'm too lazy right now to skim through the git history), but I assume this is about doing a recursive search into subdirectories.

i don't see how these two issues are related.

as for the "duplicate objects" problem: what's the problem with removing duplicates?

**Comment by porres** [comment]
Can you confirm that things work for you with 0.49.1?

And yeah, sorry, I need to better understand how things work in the Linux world. I'm missing these informations.

> the problem you tried to solve when removing support for the second, appears to be performance issues with the 1st.

Not really, there were many problems I tried to solve, the plugin was gathering all these useless Pd files that weren't real objects, it wasn't able to find objects from 'monolithic' distribution and the way it tried to handle it (with manually inserted object lists) wasn't working either. Moreover, the plugin would list "duplicates", and by duplicates I actually mean that the same object would be listed with and without a 'namespace', like there'd be two entries: "cyclone/cycle~" and "cycle~"... 

My simpler way of searching for objects also dealt with these duplicate files and now the checkbox in preferences has an actual meaning... now the objects are always listed with the 'namespace' prefix but only the object is created. If you want to create the namespace, you need to set it on the preferences and all of this is also now explained in details in the manual.

With a deep scan I am now getting duplicates and weird things, like the [bob~] object, which is already listed as part of the internals, now gets a duplicate listing of [bob/bob~]. 

I guess we can try other more sophisticated ways to scan it all and not get duplicates. I just don't know how to do it now. I don't have ideas or tried it, because I thought I had already solved it in an easy, efficient and elegant way :)
