### ISSUE TITLE
intelligent deep scanning

### ISSUE THREAD

**Issue by porres** [porres/completion-plugin#30]
taking from https://github.com/porres/completion-plugin/issues/23

we need an intelligent way for "deep scanning" for externals without getting too much garbage. I'm using this issue to keep track of thing that are on the way and stuff.

topics:
- avoiding things like bob~/bob~ inside 'extra'. 
- add support for 'sys_tmpdir' as well

**Comment by umlaeute** [comment]
> avoiding things like bob~/bob~ inside 'extra'.

is this an `extra/` problem? e.g. if i install the `constantq~` library via deken into your docsdir, i guess it also shows up as `constantq~/constantq~`

also, neither `bob~/bob~` nor `constantq~/constantq~` is actual *garbage*: these are totally valid object names.

in any case, they should be easy to detect, as they all follow the `<name>/<name>` scheme. so a regular expression like `^([^/]*)/\1$` should do the trick...

**Comment by porres** [comment]
> is this an extra/ problem?

no, not only and I was aware, the other particular 'extra' problem is that bob~ (and others) is already listed and doesn't need a duplicate.

As for 'constantq~' there is no harm in listing it as 'constantq~/constantq~'

**Comment by porres** [comment]
> ^([^/]*)/\1$

would you mind telling me what this means or pointing me to a documentation?

**Comment by umlaeute** [comment]
> the other particular 'extra' problem is that bob~ (and others) is already listed and doesn't need a duplicate.

so don't list it explicitely, and instead rely on detecting it properly?

> > ^([^/]*)/\1$
> 
> would you mind telling me what this means or pointing me to a documentation?

- `man 7 regex`
- https://en.wikipedia.org/wiki/Regular_expression

**Comment by porres** [comment]
> so don't list it explicitely, and instead rely on detecting it properly?

yup, that's one idea... anyway, this is just a thing that is happening and that I listed to take care of

> man 7 regex

sorry. what is this? tried it in the terminal and got nothing

**Comment by porres** [comment]
> add support for 'sys_tmpdir' as well

@umlaeute I copied this from you, did you mean sys_temppath?

**Comment by umlaeute** [comment]
> > man 7 regex
> 
> sorry. what is this? tried it in the terminal and got nothing

ah, it seems that macOS are missing a number of manpages.
a quick google search for `man 7 regex` should return this though https://www.man7.org/linux/man-pages/man7/regex.7.html

and i just found that `man 7 re_format` should work (and on my Linux system this is just an alias for `regex`, so probably the latter is a Linux-specific convenience link)

**Comment by umlaeute** [comment]
> @umlaeute I copied this from you, did you mean sys_temppath?

ah sorry, i was writing that from my phone. check the Pd-sources for the actual varname.

**Comment by porres** [comment]
> check the Pd-sources for the actual varname.

seems like 'sys_temppath', though I wonder what it is

**Comment by porres** [comment]
anyway, dealing with 'extra' is easy... I added the temppath even though I don't know what it is, but here is the main challenge for "deep scanning"...

The plugin searches through the main places and scans subfolders, which is cool, nice and smart. So if you have something inside 'extra' or 'docsdir/externals' it finds it and also keeps the namespace prefix for all objects. I really like this...

The problem when grabbing all user added paths is that I can have else inside 'docsdir/externals', which is one path that is added to the search paths, so else gets scanned and its objects are marked as 'else/whatever'. Not a problem so far, but.... the thing is that I can ALSO have ELSE added to the search paths. 

This is bad because it then collects all objects from ELSE without the namespace prefix and adds 'duplicates', or better, 'noise'.

This is what I have to think about how to filter...

**Comment by porres** [comment]
it is also quite bad that it scans 'else' twice, which is quite a big library with almost 500 externals... not efficient...

**Comment by porres** [comment]
I think I got this. Gonna make more tests...

What I really really wanted to take care of is fix what broke from 0.52-1 to 0.52-2 , see https://github.com/porres/completion-plugin/issues/32 I wonder if you can help me with that.

**Comment by porres** [comment]
> I think I got this.

what I do is I add the path's that have beed searched and then prevent to search what's already been searched before... seemed easy in the end and it's efficient.

**Comment by umlaeute** [comment]
> seems like 'sys_temppath', though I wonder what it is

it's the paths that are added via the `-path` cmdline flags.
they are distinct from the paths added via the `Preferences->Path` because they are ephemeral (and the paths in the preferences are persistent).

it seems you currently do
- pre-populate the object list with internals and those found in `extra/`
- check if `pd_docsdir` is available and if so search this
- search `::sys_staticpath` and `::sys_temppath`
  - filtering out objects known to be in `extra/`
- search `::sys_searchpath`

### extra
as said before, i think the extra/ handling is currently broken: why don't you just omit them from the pre-populated list and then pick them up as you encounter them in one of temp/search/static-path? that should reduce code-complexity and automatically pick up any changes to extra/ (e.g. the removal of `output~`)
it will *also* pick up `fiddle~` right now (which is currently omitted for whatever reasons).

### docsdir vs searchpath
if docsdir is enabled, it will automatically add ::pd_docsdir::externals_path to the `::sys_searchpath` (because otherwise Pd would not find it).
so there really is no need to special-case the docsdir in any way, there's not even a need to handle it explicitly at all: if you just search `[concat $::sys_temppath $::sys_searchpath $::sys_staticpath]`, you will automatically pickup all files that are accessible to the user.

### search order
for the completion-plugin i think the order in which paths are searched is irrelevant.
for completeness sake: they are searched in the order as returned by `[concat $::sys_temppath $::sys_searchpath $::sys_staticpath]`

**Comment by umlaeute** [comment]
it seems you currently do
- pre-populate the object list with internals and those found in `extra/`
- check if `pd_docsdir` is available and if so search this
- search `::sys_staticpath` and `::sys_temppath`
  - filtering out objects known to be in `extra/`
- search `::sys_searchpath`

### extra
as said before, i think the extra/ handling is currently broken: why don't you just omit them from the pre-populated list and then pick them up as you encounter them in one of temp/search/static-path? that should reduce code-complexity and automatically pick up any changes to extra/ (e.g. the removal of `output~`)
it will *also* pick up `fiddle~` right now (which is currently omitted for whatever reasons).

### docsdir vs searchpath
if docsdir is enabled, it will automatically add ::pd_docsdir::externals_path to the `::sys_searchpath` (because otherwise Pd would not find it).
so there really is no need to special-case the docsdir in any way, there's not even a need to handle it explicitly at all: if you just search `[concat $::sys_temppath $::sys_searchpath $::sys_staticpath]`, you will automatically pickup all files that are accessible to the user.

### search order
for the completion-plugin i think the order in which paths are searched is irrelevant.
for completeness sake: they are searched in the order as returned by `[concat $::sys_temppath $::sys_searchpath $::sys_staticpath]`

**Comment by porres** [comment]
> it's the paths that are added via the -path cmdline flags.

what about the ones in [declare]?

thanks for the other information, I'll revise things

**Comment by umlaeute** [comment]
`[declare -path]` is indeed unknown to the canvas... :-/
